name: Auto Assign

on:
  issues:
    types: [opened, reopened]

  pull_request:
    types: [opened, reopened]

concurrency:
  group: auto-assign-${{ github.ref }} # Group runs by the current ref to avoid conflicts
  cancel-in-progress: true

jobs:
  auto-assign:
    # Restrict workflow execution to repositories owned by 'magnidev'.
    # This is intentional for internal use. Forks or external contributions will not execute this workflow.
    if: github.repository_owner == 'magnidev'
    name: Auto Assign Issue or PR
    uses: magnidev/automation/.github/workflows/auto-assign.yml@main
    with:
      assignees: "fermeridamagni"
      numOfAssignee: 1
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
