name: CI # Continuous Integration Workflow

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run on pull requests targeting the main branch

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }} # Cancel in-progress runs for branches other than main

jobs:
  scripts:
    # Restrict workflow execution to repositories owned by 'magnidev'.
    # This is intentional for internal use. Forks or external contributions will not execute this workflow.
    if: github.repository_owner == 'magnidev'
    uses: magnidev/automation/.github/workflows/run.yml@main # Reuse the run workflow from the magnidev/automation repository
    secrets: "inherit" # Inherit secrets from the parent workflow
    with:
      commands: >
        [
          "lint",
          "format:check",
          "build",
          "test"
        ]
      # The 'commands' input specifies the commands to run in the CI workflow.
