name: CI

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run on pull requests targeting the main branch

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  scripts:
    # Restrict workflow execution to repositories owned by 'magnidev'.
    # This is intentional for internal use. Forks or external contributions will not execute this workflow.
    if: github.repository_owner == 'magnidev'
    uses: magnidev/automation/.github/workflows/run.yml@main # Reuse the run workflow from the magnidev/automation repository
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
    with:
      commands: >
        [
          "lint",
          "format:check",
          "build",
          "test"
        ]
