name: preview package

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  detect-package:
    name: Detect Package
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{ steps.detect.outputs.package_name }}
      version: ${{ steps.detect.outputs.version }}
      is_prerelease: ${{ steps.detect.outputs.is_prerelease }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect package
        id: detect
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT

  preview:
    # restrict workflow execution to repositories owned by 'magnidev'.
    # this is intentional for internal use. forks or external contributions will not execute this workflow.
    if: github.repository_owner == 'magnidev'
    needs: detect-package
    uses: magnidev/automation/.github/workflows/preview-package.yml@main
    secrets:
      bot_app_id: ${{ secrets.bot_app_id }}
      bot_private_key: ${{ secrets.bot_private_key }}
    with:
      publish_directories: ./packages/${{ needs.detect-package.outputs.package_name }}/
